// ─── Toni aggiuntivi per il tab Descrizioni ──────────────────────────────────
// Aggiunge toni alle sotto-categorie esistenti senza toccare DETAILS_DB inline.
// Mergiato a runtime in DescriptionsPage.
//   - inquietante : confluisce nel tono "Cupo" insieme al 'dark' di DETAILS_DB
//   - sfarzoso    : opulento / nobile
//   - steampunk   : gaslamp/industriale (stile Zeitgeist: Flint, vapore, rivoluzione)
// CAMPIONE: luoghi + locande (gli altri arrivano a lotti).

export const DETAILS_EXTRA = {
  luoghi: {
    foresta: {
      sfarzoso: [
        { key: "radura dorata", note: "luce che cade come polvere d'oro tra foglie di un verde perfetto" },
        { key: "fiori mai visti", note: "petali iridescenti che profumano di miele e spezie pregiate" },
        { key: "sentiero curato", note: "ghiaia chiara e siepi potate, come il parco di un palazzo" },
        { key: "alberi argentei", note: "cortecce lisce che riflettono la luce come metallo lucidato" },
        { key: "fontana tra le radici", note: "acqua cristallina sgorga da una conchiglia di pietra intagliata" },
        { key: "uccelli dal piumaggio vivido", note: "canti melodiosi, code lunghe come stoffe di seta" },
        { key: "frutti lucenti", note: "pendono bassi e profumati, quasi invitassero a un banchetto" },
        { key: "quiete ariosa", note: "l'aria sa di fiori d'arancio, ogni cosa è in ordine e abbondante" },
      ],
      inquietante: [
        { key: "alberi che osservano", note: "nodi nella corteccia disposti come occhi che ti seguono" },
        { key: "silenzio che ascolta", note: "ogni tuo rumore pare amplificato, come se qualcosa contasse i passi" },
        { key: "carne tra le radici", note: "qualcosa di rosa e umido pulsa piano sotto il muschio" },
        { key: "voci di bambini", note: "risate lontane dove non dovrebbe esserci nessuno" },
        { key: "alberi sanguinanti", note: "linfa rosso scuro cola da tagli che nessuno ha inciso" },
        { key: "odore di ferro", note: "metallico e caldo, come una stanza dopo una macellazione" },
        { key: "impronte che ti seguono", note: "le tue, ma fresche e sovrapposte, come avessi già camminato qui" },
        { key: "rami che si chiudono", note: "il sentiero alle tue spalle è più stretto di quando sei passato" },
      ],
      steampunk: [
        { key: "pali del telegrafo", note: "fili ronzanti tesi tra gli alberi, spariscono verso la città" },
        { key: "binari nel sottobosco", note: "rotaie arrugginite invase dall'edera, una vecchia linea mineraria" },
        { key: "fuliggine sulle foglie", note: "una patina grigia si deposita, il vento porta odore di carbone" },
        { key: "macchinario abbandonato", note: "una caldaia rugginosa tra le felci, valvole ormai fredde" },
        { key: "paletti di rilievo", note: "picchetti numerati e nastri: qualcuno ha misurato questi alberi" },
        { key: "ceppi netti", note: "tagli regolari di sega a vapore, intere file di alberi abbattuti" },
        { key: "ruscello iridescente", note: "una pellicola oleosa sull'acqua, riflessi azzurro-viola" },
        { key: "fischio lontano", note: "il sibilo di un treno o di una sirena di fabbrica oltre le chiome" },
      ],
    },
    dungeon: {
      sfarzoso: [
        { key: "sarcofagi dorati", note: "coperchi scolpiti con volti sereni, foglia d'oro ancora intatta" },
        { key: "mosaici alle pareti", note: "tessere di lapislazzuli e madreperla, scene di trionfo" },
        { key: "catene d'argento", note: "reggono lampade spente incrostate di gemme" },
        { key: "pavimento intarsiato", note: "marmi policromi in motivi geometrici perfetti" },
        { key: "tesoro impolverato", note: "monete e calici accatastati, lo splendore soffocato dalla polvere" },
        { key: "colonne scanalate", note: "capitelli dorati, troppo eleganti per un luogo sepolto" },
        { key: "incenso vecchio", note: "resine pregiate bruciate secoli fa, ancora persistenti" },
        { key: "porte di bronzo lucido", note: "bassorilievi che narrano la gloria di chi vi riposa" },
      ],
      inquietante: [
        { key: "graffi sulle pareti", note: "fitti, all'altezza delle dita, fatti dall'interno" },
        { key: "stillicidio caldo", note: "le gocce sono tiepide, e non sono d'acqua" },
        { key: "porte che respirano", note: "il legno si gonfia e si ritira piano, come un torace" },
        { key: "ossa disposte", note: "non sparse: allineate, ordinate da qualcuno con cura" },
        { key: "eco in ritardo", note: "i tuoi passi risuonano un attimo dopo, e di troppo" },
        { key: "macchie che colano in su", note: "scure, risalgono il muro contro ogni logica" },
        { key: "respiro nel buio", note: "lento e paziente, sempre alla stessa distanza da te" },
        { key: "odore dolciastro", note: "marcio e zuccherino insieme, si attacca alla gola" },
      ],
      steampunk: [
        { key: "tubature ronzanti", note: "condotte di rame corrono lungo le pareti, calde al tatto" },
        { key: "ingranaggi nel muro", note: "ruote dentate semivisibili girano lente dietro una grata" },
        { key: "manometri appannati", note: "quadranti di ottone con lancette ferme su valori critici" },
        { key: "lampada a gas", note: "una fiammella azzurra dietro il vetro, sibila piano" },
        { key: "vapore dalle fessure", note: "sbuffi caldi escono dalle giunture del pavimento" },
        { key: "scala a chiocciola di ferro", note: "gradini grigliati che risuonano, ruggine alle ringhiere" },
        { key: "odore di olio e carbone", note: "denso, industriale, si attacca ai vestiti" },
        { key: "pulsantiera di ottone", note: "leve e valvole, alcune bloccate dalla ruggine" },
      ],
    },
    "città": {
      sfarzoso: [
        { key: "facciate affrescate", note: "palazzi con balconi dorati e stemmi dipinti a vivaci colori" },
        { key: "fontana monumentale", note: "marmo bianco, zampilli che brillano, monete sul fondo" },
        { key: "spezie costose", note: "zafferano e incenso da botteghe dalle insegne dorate" },
        { key: "carrozze laccate", note: "cavalli bardati di velluto, scortati da servitori in livrea" },
        { key: "lastricato pulito", note: "pietra chiara lavata di fresco, nessun rifiuto in vista" },
        { key: "abiti di seta", note: "passanti in broccato e gioielli, risate misurate" },
        { key: "giardini pensili", note: "verzura curata che cola dai terrazzi dei nobili" },
        { key: "musica da una loggia", note: "liuti e voci educate filtrano da finestre illuminate" },
      ],
      inquietante: [
        { key: "finestre sbarrate", note: "assi inchiodate dall'esterno, croci di calce sulle porte" },
        { key: "campana a morto", note: "rintocchi lenti, nessuno per strada a contarli con te" },
        { key: "odore di pira", note: "fumo grasso e dolciastro dai quartieri bassi" },
        { key: "occhi alle persiane", note: "ti osservano e si ritirano appena ricambi lo sguardo" },
        { key: "carretto coperto", note: "lo spingono in silenzio, da sotto il telo spuntano piedi" },
        { key: "gesso sulle porte", note: "numeri e simboli; alcune case ne hanno tre, altre nessuno" },
        { key: "mercato muto", note: "banchi pieni di merce, nessun venditore, nessun rumore" },
        { key: "bambini fermi", note: "in fila contro un muro, ti fissano senza una parola" },
      ],
      steampunk: [
        { key: "ciminiere fumanti", note: "il cielo è velato di fumo, il sole è un disco arancione" },
        { key: "tram a vapore", note: "vagoni che sferragliano su rotaie, sbuffi a ogni fermata" },
        { key: "lampioni a gas", note: "luce gialla e tremula, un lampionaio li accende con l'asta" },
        { key: "manifesti rivoluzionari", note: "incollati sui muri, strappati a metà, slogan contro la corona" },
        { key: "fabbriche rumorose", note: "il battito dei magli scuote i vetri, operai in fila al cambio turno" },
        { key: "cavi aerei", note: "matasse di fili telegrafici ed elettrici incrociano le strade" },
        { key: "fanghiglia di carbone", note: "rigagnoli neri lungo i marciapiedi, impronte unte" },
        { key: "automa di servizio", note: "un congegno di ottone spazza la piazza a scatti" },
        { key: "edicola del giornalaio", note: "pile di quotidiani, titoli sull'ultimo comizio e sui treni in ritardo" },
        { key: "ponte di ferro chiodato", note: "vibra al passaggio dei carri, sotto scorre un canale oleoso" },
        { key: "agente in uniforme", note: "manganello e fischietto, osserva la folla con sospetto" },
        { key: "comizio all'angolo", note: "un oratore su una cassa, capannello che annuisce e brontola" },
        { key: "carro dei pompieri a vapore", note: "ottoni lucidi e una pompa fumante, cavalli al galoppo" },
        { key: "orologio pubblico", note: "su una torre di mattoni, scandisce i turni di mezza città" },
        { key: "manovali in pausa", note: "seduti sul cordolo, gavetta in mano, fuliggine sui volti" },
      ],
    },
    rovine: {
      sfarzoso: [
        { key: "colonne ancora dritte", note: "marmo venato che regge un cielo aperto, eleganza ostinata" },
        { key: "mosaico sotto le erbacce", note: "tessere d'oro disegnano ancora un sole" },
        { key: "arco trionfale", note: "iscrizioni celebrative illeggibili ma ancora imponenti" },
        { key: "statue decapitate", note: "corpi in posa regale, vesti scolpite con maestria" },
        { key: "scalinata maestosa", note: "gradini larghi e consumati, salgono a una soglia vuota" },
        { key: "fontana di porfido", note: "vasche secche, rubinetti a forma di leone" },
        { key: "affreschi sbiaditi", note: "figure incoronate a banchetto, colori spenti dal tempo" },
        { key: "cancello in ferro battuto", note: "volute elaborate arrugginite, un tempo costose" },
      ],
      inquietante: [
        { key: "altari rovesciati", note: "pietra annerita, scanalature che convogliano verso una coppa" },
        { key: "nomi raschiati", note: "qualcuno ha cancellato ogni nome dalle iscrizioni" },
        { key: "vento che parla", note: "tra le pietre forma sillabe che quasi capisci" },
        { key: "cerchio bruciato", note: "l'erba non ricresce, la terra dentro è vetrificata" },
        { key: "statue rivolte all'interno", note: "tutte verso un punto centrale, come in attesa" },
        { key: "ossa nei muri", note: "murate nelle pareti, troppe per essere un caso" },
        { key: "freddo improvviso", note: "in una stanza l'aria gela, il fiato si condensa d'estate" },
        { key: "porta che non c'era", note: "una soglia nuova in un muro che avevi già guardato" },
      ],
      steampunk: [
        { key: "fabbrica sventrata", note: "tetto crollato su telai arrugginiti, cinghie pendono spezzate" },
        { key: "caldaia esplosa", note: "lamiere contorte verso l'esterno, segni di un'antica deflagrazione" },
        { key: "binari divelti", note: "rotaie ritorte verso il cielo, traversine marce" },
        { key: "quadranti infranti", note: "strumenti di misura a terra, vetri rotti, lancette piegate" },
        { key: "ciminiera spezzata", note: "monca a metà, mattoni anneriti sparsi alla base" },
        { key: "ingranaggi giganti", note: "ruote dentate più alte di un uomo, bloccate dalla ruggine" },
        { key: "odore di metallo bagnato", note: "ferro ossidato e pioggia, un sapore in gola" },
        { key: "graffiti operai", note: "nomi e date incisi nel metallo, un turno che non è più tornato" },
      ],
    },
  },
  locande: {
    esterno: {
      sfarzoso: [
        { key: "insegna dorata", note: "intagliata e laccata, dondola con un cigolio quasi musicale" },
        { key: "lanterne di vetro colorato", note: "luce calda che tinge la strada di ambra e rubino" },
        { key: "stalliere in livrea", note: "accoglie i cavalli con guanti puliti e un inchino" },
        { key: "vetrate piombate", note: "finestre ampie che mostrano sale illuminate e dorate" },
        { key: "tappeto fino alla soglia", note: "rosso, spazzato di fresco, fino al gradino di marmo" },
        { key: "arrosto pregiato", note: "selvaggina speziata e vino caldo che invitano dentro" },
        { key: "facciata a graticcio dipinta", note: "travi scure, intonaco crema, fiori alle finestre" },
        { key: "voci allegre e ovattate", note: "risate ricche e musica discreta filtrano fuori" },
      ],
      inquietante: [
        { key: "insegna scrostata", note: "il nome è illeggibile, resta una figura che digrigna" },
        { key: "finestre buie", note: "nessuna luce, eppure dentro qualcosa si muove" },
        { key: "silenzio sospetto", note: "stalle piene di cavalli, ma la locanda è muta" },
        { key: "porta socchiusa", note: "oscilla appena, da dentro un odore di rancido" },
        { key: "cane alla catena", note: "fissa la porta, ringhia, non smette di tremare" },
        { key: "fango rosso alla soglia", note: "impronte che entrano, nessuna che esce" },
        { key: "lanterna spenta che oscilla", note: "senza vento, cigola avanti e indietro" },
        { key: "avviso inchiodato", note: "una preghiera contro qualcosa, lettere fatte in fretta" },
      ],
      steampunk: [
        { key: "insegna al gas", note: "lettere illuminate da fiammelle dietro il vetro smerigliato" },
        { key: "scarico fumante", note: "sbuffi di vapore escono da una valvola sul muro laterale" },
        { key: "velocipedi appoggiati", note: "ruote alte e telai di ottone allineati contro il muro" },
        { key: "manifesto dei traghetti", note: "orari dei battelli a vapore e tariffe, incorniciato" },
        { key: "lampione ronzante", note: "accanto alla porta, attira falene, luce gialla" },
        { key: "grata fumante", note: "vapore caldo sale dalle cantine sotto il marciapiede" },
        { key: "odore di birra e carbone", note: "il tepore industriale si mescola al malto" },
        { key: "campanello pneumatico", note: "premi un pistone d'ottone e un fischio annuncia dentro" },
      ],
    },
    sala: {
      sfarzoso: [
        { key: "lampadario a candele", note: "decine di fiamme su ferro dorato, cera che gocciola lenta" },
        { key: "camino monumentale", note: "marmo intagliato, fuoco vivo, stemmi sopra la cappa" },
        { key: "boccali d'argento", note: "lucidi, serviti da personale in grembiule immacolato" },
        { key: "tavoli di quercia lucida", note: "legno oliato, tovaglie pulite, niente macchie" },
        { key: "arazzo alla parete", note: "scene di caccia tessute in fili d'oro e cremisi" },
        { key: "musico d'angolo", note: "un liuto suonato con grazia, una voce educata" },
        { key: "profumo di cera e vino", note: "ambiente caldo e ricco, ogni dettaglio curato" },
        { key: "avventori eleganti", note: "mercanti e nobili minori, conversazioni a bassa voce" },
      ],
      inquietante: [
        { key: "silenzio all'ingresso", note: "tutti smettono di parlare e ti fissano un istante di troppo" },
        { key: "oste che sorride poco", note: "ti serve senza guardarti, le mani gli tremano" },
        { key: "macchia sul pavimento", note: "lavata male, di un marrone che il legno ha assorbito" },
        { key: "sedia sempre vuota", note: "apparecchiata, nessuno ci si siede né la guarda" },
        { key: "fuoco che non scalda", note: "le fiamme ci sono ma la sala resta fredda" },
        { key: "avventori immobili", note: "boccali pieni, nessuno beve, nessuno parla davvero" },
        { key: "graffi sotto il tavolo", note: "solchi di unghie nel legno, dove ci si aggrappa" },
        { key: "una stanza in più", note: "una porta sul retro che l'oste giura non esistere" },
      ],
      steampunk: [
        { key: "ventilatore a soffitto", note: "pale di ottone mosse da una cinghia, ronzio costante" },
        { key: "spillatrice a pressione", note: "leve cromate, la birra esce con uno sbuffo di schiuma" },
        { key: "lampade elettriche fioche", note: "filamenti aranciati nei bulbi, sfarfallano a tratti" },
        { key: "giornale sul bancone", note: "titoli cubitali sulla rivoluzione e sui treni" },
        { key: "tubo pneumatico", note: "capsule di ottone sibilano verso le cucine con gli ordini" },
        { key: "orologio a ingranaggi", note: "meccanismo a vista dietro un vetro, rintocca le mezz'ore" },
        { key: "fumo di pipa e carbone", note: "una foschia azzurrina sotto il soffitto" },
        { key: "avventori operai", note: "tute unte, mani callose, parlano di turni e di scioperi" },
      ],
    },
    camere: {
      sfarzoso: [
        { key: "letto a baldacchino", note: "tende di velluto, lenzuola di lino fresco, cuscini soffici" },
        { key: "bacile d'argento", note: "acqua profumata, asciugamani ricamati piegati con cura" },
        { key: "tappeto spesso", note: "i passi affondano, motivi orientali dai colori vivi" },
        { key: "specchio dorato", note: "vetro limpido e costoso, riflette la fiamma della candela" },
        { key: "vista sul giardino", note: "finestra ampia su aiuole curate e una fontana" },
        { key: "scrivania intarsiata", note: "calamaio di cristallo, carta pregiata, ceralacca" },
        { key: "profumo di lavanda", note: "biancheria con sacchetti d'erbe, tutto immacolato" },
        { key: "campanello di seta", note: "un cordone che chiama subito la servitù" },
      ],
      inquietante: [
        { key: "graffi sulla porta interna", note: "dall'interno: qualcuno voleva uscire e non poteva" },
        { key: "specchio coperto", note: "un telo lo nasconde, qualcuno l'ha fatto di proposito" },
        { key: "letto già sfatto", note: "l'impronta di un corpo ancora tiepida, la stanza vuota" },
        { key: "macchia al soffitto", note: "scura, a forma di figura, riappare se la imbianchi" },
        { key: "freddo verso il muro", note: "un lato gela, l'intonaco è umido al tatto" },
        { key: "nome inciso nel legno", note: "ripetuto sul davanzale decine di volte, sempre lo stesso" },
        { key: "porta che si apre da sé", note: "di notte, lentamente, senza spiffero che la giustifichi" },
        { key: "qualcosa sotto il letto", note: "non c'è niente, ma lì il pavimento è graffiato" },
      ],
      steampunk: [
        { key: "termosifone gorgogliante", note: "tubi di ghisa che ticchettano scaldandosi" },
        { key: "lampada a gas regolabile", note: "una manopola d'ottone alza e abbassa la fiamma" },
        { key: "lavabo con pompa", note: "una leva di metallo eroga acqua con uno sbuffo" },
        { key: "finestra sui tetti fumanti", note: "una distesa di comignoli e ciminiere" },
        { key: "serratura a combinazione", note: "rotelle numerate d'ottone al posto della chiave" },
        { key: "ventola nella parete", note: "gira piano, fa entrare aria che sa di città" },
        { key: "stampa di una locomotiva", note: "appesa storta, un orgoglio un po' sbiadito" },
        { key: "rumore di fondo", note: "il battito lontano delle fabbriche non si ferma mai" },
      ],
    },
  },
  negozi: {
    fabbro: {
      sfarzoso: [
        { key: "armi da parata", note: "spade cesellate e dorate, più gioielli che armi, in vetrina" },
        { key: "incudine d'argento", note: "lucidata a specchio, usata solo per i pezzi pregiati" },
        { key: "armature da cerimonia", note: "piastre incise con stemmi, smaltate, su manichini" },
        { key: "fucina ordinata", note: "attrezzi in fila per dimensione, niente fuliggine fuori posto" },
        { key: "cliente nobile", note: "un signore attende una lama su misura, servito col vino" },
        { key: "marchio del maestro", note: "ogni pezzo reca un punzone d'oro, garanzia di prestigio" },
        { key: "registro rilegato", note: "commesse di casati nobiliari in bella calligrafia" },
      ],
      steampunk: [
        { key: "magli a vapore", note: "battono il metallo con colpi ritmici che scuotono il pavimento" },
        { key: "torni e presse", note: "macchinari che sagomano canne e ingranaggi in serie" },
        { key: "scintille e mola", note: "una pioggia di faville, occhiali scuri d'obbligo" },
        { key: "canne di fucile in fila", note: "decine identiche su una rastrelliera, prodotte in catena" },
        { key: "manometro sulla caldaia", note: "l'apprendista controlla la pressione, una valvola sibila" },
        { key: "odore di olio e brunitura", note: "acre, metallico, ti resta in gola" },
        { key: "operai con grembiuli di cuoio", note: "mani annerite, gridano sopra il frastuono" },
        { key: "prototipi sotto telo", note: "qualcosa di angolare in un angolo, commessa militare?" },
        { key: "schede tecniche appese", note: "disegni quotati di meccanismi a percussione" },
        { key: "cassa di munizioni", note: "ottoni lucidi allineati, etichetta col timbro della corona" },
        { key: "saldatrice ad arco", note: "una luce accecante e azzurra, l'odore di metallo fuso" },
        { key: "morsa da banco enorme", note: "stringe una piastra mentre un operaio la lima" },
        { key: "trapano a colonna", note: "una cinghia lo collega all'albero motore sul soffitto" },
        { key: "schedario delle commesse", note: "ordini militari e civili divisi per cassetto" },
      ],
    },
    erborista: {
      sfarzoso: [
        { key: "boccette di cristallo", note: "essenze colorate con etichette dorate su scaffali di mogano" },
        { key: "profumo di rose e ambra", note: "ricco e avvolgente, niente del solito odore di erbe" },
        { key: "bilancia di precisione", note: "ottone e madreperla, pesi minuscoli in un astuccio di velluto" },
        { key: "elisir di bellezza", note: "creme e tonici per dame, prezzi sussurrati con discrezione" },
        { key: "erbario miniato", note: "un volume aperto con illustrazioni dipinte a mano" },
        { key: "servizio da tè", note: "i clienti facoltosi attendono seduti, serviti in porcellana" },
        { key: "assistente discreto", note: "guanti bianchi, voce bassa, incarta in carta velina" },
      ],
      steampunk: [
        { key: "alambicchi a serpentina", note: "vetro e rame, gorgogliano su fiamme a gas regolabili" },
        { key: "tonici brevettati", note: "file di flaconi uguali, etichette stampate e promesse miracolose" },
        { key: "odore chimico pungente", note: "acido e canfora, fa lacrimare gli occhi" },
        { key: "manometro sul distillatore", note: "pressione del vapore d'occhio, valvola di sicurezza" },
        { key: "scaffali di reagenti", note: "barattoli numerati, polveri colorate, simboli di pericolo" },
        { key: "imbottigliatrice", note: "riempie e tappa flaconi con scatti regolari" },
        { key: "réclame del tonico elettrico", note: "un manifesto con un uomo vigoroso e raggiante" },
        { key: "fornello a petrolio", note: "fiamma azzurra costante sotto una storta annerita" },
        { key: "guanti e mascherina", note: "il droghiere lavora protetto, qualcosa qui morde la pelle" },
        { key: "registro all'ingrosso", note: "ordini per fabbriche e ospedali, quantità enormi" },
        { key: "centrifuga ronzante", note: "separa liquidi in provette, vibra sul banco" },
        { key: "armadietto refrigerato", note: "ghiaccio e serpentine tengono al fresco le fiale" },
        { key: "bilancia automatica", note: "dosa le polveri con un meccanismo a contrappesi" },
        { key: "manifesto sanitario", note: "norme d'igiene affisse, timbrate dal comune" },
      ],
    },
    mercante: {
      sfarzoso: [
        { key: "sete e broccati", note: "rotoli di stoffe pregiate srotolati su un bancone lucido" },
        { key: "spezie esotiche", note: "in coppe d'ottone, profumi di terre lontane" },
        { key: "oggetti d'importazione", note: "ventagli, lacche, porcellane da oltre il mare" },
        { key: "mercante affabile", note: "abito curato, modi melliflui, ricorda il tuo nome" },
        { key: "gioielli in vetrina", note: "sotto vetro, su velluto nero, illuminati da candele" },
        { key: "libro mastro elegante", note: "conti tenuti con cura, sigilli di ceralacca" },
        { key: "garzone in livrea", note: "porta i pacchi alla carrozza con un inchino" },
      ],
      steampunk: [
        { key: "merci in serie", note: "scaffali fino al soffitto di prodotti identici e confezionati" },
        { key: "registratore di cassa", note: "una macchina d'ottone che tintinna e stampa lo scontrino" },
        { key: "vetrina illuminata a gas", note: "manichini con abiti pronti, cartellini coi prezzi fissi" },
        { key: "montacarichi", note: "una piattaforma a fune porta le casse al piano di sopra" },
        { key: "tubo pneumatico dei pagamenti", note: "capsule sibilano verso la cassa centrale" },
        { key: "cataloghi illustrati", note: "ordini per corrispondenza, consegna su rotaia" },
        { key: "réclame ovunque", note: "manifesti colorati che vantano novità e modernità" },
        { key: "odore di nuovo", note: "vernice, carta da imballaggio, gomma, metallo lucido" },
        { key: "folla di clienti", note: "gente comune riempie i cesti, voci e spintoni" },
        { key: "automa in vetrina", note: "gira lentamente mostrando un cappotto" },
        { key: "nastro trasportatore", note: "porta i pacchi dal retro alla cassa con un ronzio" },
        { key: "insegna luminosa a gas", note: "lettere disegnate da decine di fiammelle" },
        { key: "reparto novità elettriche", note: "lampade, ventole e gingilli che ronzano sotto vetro" },
        { key: "fattorino in bicicletta", note: "carica le consegne in un cesto di vimini sul manubrio" },
      ],
    },
  },
  png: {
    umano: {
      sfarzoso: [
        { key: "abiti su misura", note: "broccato e bottoni d'argento, scarpe lucide senza un graffio" },
        { key: "anelli a ogni dito", note: "gemme che catturano la luce mentre gesticola" },
        { key: "portamento altero", note: "mento alto, sguardo che misura chi ha davanti" },
        { key: "profumo costoso", note: "lo precede e lo segue, fiori e muschio" },
        { key: "voce educata", note: "parole scelte, un sorriso che non scalda" },
        { key: "servitore al seguito", note: "un passo indietro, pronto a ogni cenno" },
      ],
      steampunk: [
        { key: "occhiali da officina", note: "alzati sulla fronte, un alone pulito tra la fuliggine" },
        { key: "mani callose e annerite", note: "olio nelle pieghe, un dito fasciato" },
        { key: "bretelle e camicia arrotolata", note: "abiti pratici, una chiave nel taschino" },
        { key: "tosse di fabbrica", note: "profonda, la porta con sé da troppi turni" },
        { key: "orologio da tasca ammaccato", note: "lo consulta spesso, schiavo del cambio turno" },
        { key: "spilla del sindacato", note: "discreta sul bavero, la mostra solo ai fidati" },
        { key: "odore di carbone e sudore", note: "il marchio di chi vive accanto alle macchine" },
        { key: "cappello a cilindro lucido", note: "un industriale, catena dell'orologio sul panciotto teso" },
        { key: "fasciatura su una mano", note: "un infortunio sul lavoro, ancora fresco" },
        { key: "distintivo da caposquadra", note: "ben in vista, conta gli uomini con lo sguardo" },
        { key: "occhiaie da doppio turno", note: "sveglio da troppo, parla a scatti" },
        { key: "tasca piena di volantini", note: "li distribuisce di nascosto, guardandosi attorno" },
      ],
    },
    nano: {
      sfarzoso: [
        { key: "barba con fili d'oro", note: "perline preziose, ogni treccia un casato" },
        { key: "armatura cerimoniale", note: "piastre lucide incise, più ornamento che difesa" },
        { key: "boccale tempestato di gemme", note: "non lo posa mai, neanche parlando d'affari" },
        { key: "anelli di gilda", note: "sigilli da maestro artigiano, garanzia di rango" },
        { key: "voce profonda e misurata", note: "parla di lignaggio e di debiti d'onore" },
        { key: "mantello foderato di pelliccia", note: "spilla d'argento a forma di incudine" },
      ],
      steampunk: [
        { key: "barba legata in rete", note: "per non impigliarla negli ingranaggi" },
        { key: "braccio meccanico", note: "una protesi d'ottone, dita che ticchettano" },
        { key: "cintura porta-attrezzi", note: "chiavi e calibri a portata di mano, tutto in ordine" },
        { key: "occhiali a lenti multiple", note: "le ribalta per esaminare meccanismi minuti" },
        { key: "voce roca dal fumo", note: "grida ordini sopra il frastuono della fonderia" },
        { key: "tasche piene di bulloni", note: "tintinnano quando cammina" },
        { key: "orgoglio dell'ingegnere", note: "parla delle sue macchine come di figli" },
        { key: "saldatura recente sulla protesi", note: "una riparazione fatta in fretta, ancora annerita" },
        { key: "metro pieghevole in tasca", note: "lo estrae per misurare tutto, per abitudine" },
        { key: "lente da gioielliere all'occhio", note: "incastrata, non la toglie nemmeno parlando" },
        { key: "tatuaggio di gilda", note: "un ingranaggio sull'avambraccio, sbiadito dagli anni" },
        { key: "borsa di cuoio pesante", note: "tintinna di strumenti, la posa con un tonfo" },
      ],
    },
    elfo: {
      sfarzoso: [
        { key: "vesti di seta cangiante", note: "colori che mutano con la luce, ricami sottili" },
        { key: "diadema d'argento", note: "posato con noncuranza tra i capelli lunghi" },
        { key: "movenze aggraziate", note: "ogni gesto sembra provato, mai un'esitazione" },
        { key: "sguardo distante", note: "ti osserva come da una grande altezza" },
        { key: "gioielli antichi", note: "valgono più di un villaggio, portati con leggerezza" },
        { key: "voce melodiosa", note: "parla piano, costringe gli altri ad avvicinarsi" },
      ],
      steampunk: [
        { key: "occhialini di precisione", note: "lenti su un'astina d'argento, per il lavoro fine" },
        { key: "abito sobrio e impeccabile", note: "panno scuro, tasche per gli strumenti, niente fronzoli" },
        { key: "dita macchiate d'inchiostro", note: "disegnatore o orologiaio, mani ferme" },
        { key: "taccuino di schizzi", note: "meccanismi eleganti annotati con cura maniacale" },
        { key: "disprezzo per il rumore", note: "lavora isolato, dove il fragore non arriva" },
        { key: "spilla a ingranaggio", note: "argento brunito, un tocco di stile" },
        { key: "voce paziente", note: "spiega come a un bambino, senza alzare il tono" },
      ],
    },
    gnomo: {
      sfarzoso: [
        { key: "vestito eccentrico e costoso", note: "panciotto ricamato, troppi colori, gusto sicuro" },
        { key: "monocolo gemmato", note: "lo regola di continuo, più vezzo che necessità" },
        { key: "tasche piene di curiosità", note: "ninnoli preziosi che mostra con orgoglio" },
        { key: "voce vivace e arguta", note: "battute rapide, ride delle proprie spiritosaggini" },
        { key: "scarpe con fibbie d'oro", note: "lucide, col tacco per guadagnare un dito" },
        { key: "collezione al collo", note: "medaglioni e cammei, ognuno con una storia" },
      ],
      steampunk: [
        { key: "capelli bruciacchiati", note: "un esperimento andato di traverso, di recente" },
        { key: "cinturone di aggeggi", note: "lenti, molle, fiale, un piccolo cannello" },
        { key: "occhiali fumé sollevati", note: "occhi spalancati ed entusiasti sotto" },
        { key: "dita macchiate di reagenti", note: "colori che non vanno via, ne va fiero" },
        { key: "parla a raffica", note: "idee più veloci delle parole, salta da un tema all'altro" },
        { key: "marchingegno che ticchetta", note: "in tasca, non dice cosa sia, sorride" },
        { key: "odore di ozono", note: "qualcosa di elettrico lo segue ovunque" },
      ],
    },
    halfling: {
      sfarzoso: [
        { key: "panciotto di velluto", note: "bottoni di madreperla che faticano a chiudersi" },
        { key: "catena dell'orologio dorata", note: "attraversa il ventre, un orologio che non guarda" },
        { key: "modi cordiali e calorosi", note: "ti offre da bere prima di sapere chi sei" },
        { key: "anello con sigillo", note: "di una famiglia di mercanti benestanti" },
        { key: "profumo di pane e burro", note: "buono, rassicurante, costoso a modo suo" },
        { key: "voce allegra", note: "ride spesso, ma gli occhi contano le monete" },
      ],
      steampunk: [
        { key: "tuta da macchinista", note: "rimboccata e cucita su misura per la sua statura" },
        { key: "berretto con occhiali", note: "spinto all'indietro, una macchia d'olio sulla guancia" },
        { key: "mani veloci e abili", note: "infila le dita nei meccanismi dove gli altri non arrivano" },
        { key: "fischietto al collo", note: "segnala i turni o i guai sulla linea" },
        { key: "tasche di stoppa e grasso", note: "sempre pronto a tappare una perdita" },
        { key: "passo svelto tra le macchine", note: "conosce ogni tubo e valvola a memoria" },
        { key: "buonumore ostinato", note: "canticchia anche sotto il fragore dei magli" },
      ],
    },
    tiefling: {
      sfarzoso: [
        { key: "abito nero e oro", note: "elegante e drammatico, corna ornate di anelli" },
        { key: "gemme nelle corna", note: "piccole, scintillanti, una vanità deliberata" },
        { key: "sguardo che provoca", note: "sa l'effetto che fa e ne gode" },
        { key: "profumo di incenso e cuoio", note: "caldo, speziato, un po' inquietante" },
        { key: "voce vellutata", note: "ogni parola sembra avere un secondo significato" },
        { key: "guanti finissimi", note: "non li toglie mai del tutto" },
      ],
      steampunk: [
        { key: "cappotto lungo e fuligginoso", note: "bavero alzato, tasche profonde piene di chissà cosa" },
        { key: "lenti colorate", note: "tinte di rosso, nascondono in parte gli occhi" },
        { key: "corna con anelli di ferro", note: "funzionali, ci aggancia qualcosa quando serve" },
        { key: "mani che armeggiano", note: "con un congegno che non smette di sistemare" },
        { key: "odore di zolfo e olio", note: "naturale e industriale insieme, indistinguibili" },
        { key: "aria da agitatore", note: "parla di diritti e di padroni con un sorriso storto" },
        { key: "voce bassa nel frastuono", note: "ti costringe ad avvicinarti per sentire" },
      ],
    },
    mezzorco: {
      sfarzoso: [
        { key: "abiti ricchi su spalle larghe", note: "broccato teso sulla corporatura imponente" },
        { key: "zanne con cerchietti d'oro", note: "un ornamento che sfida chi lo guarda storto" },
        { key: "modi raffinati", note: "posata in mano, parole misurate, a sorpresa" },
        { key: "cicatrice incorniciata", note: "non la nasconde, la porta come un gioiello" },
        { key: "voce profonda e controllata", note: "abbassa il tono di proposito, e tutti tacciono" },
        { key: "mantello pregiato", note: "fermaglio d'argento, foderato di rosso" },
      ],
      steampunk: [
        { key: "forza messa al lavoro", note: "sposta da solo casse che servirebbero in tre" },
        { key: "grembiule bruciacchiato", note: "scintille e schegge non lo fermano" },
        { key: "guanti rinforzati", note: "afferra il metallo rovente con disinvoltura" },
        { key: "spalle segnate dalle cinghie", note: "anni a trainare e caricare alla fonderia" },
        { key: "voce che copre i magli", note: "non deve gridare, basta che parli" },
        { key: "attrezzo enorme in spalla", note: "una mazza o una chiave grande quanto un braccio" },
        { key: "sguardo stanco ma fermo", note: "doppi turni, paga magra, niente lamentele" },
      ],
    },
  },
  architettura: {
    porte: {
      sfarzoso: [
        { key: "portale intagliato", note: "noce con scene mitologiche, maniglie dorate" },
        { key: "battenti di bronzo", note: "teste di leone che reggono anelli pesanti" },
        { key: "soglia in marmo", note: "venato, consumato al centro da passi illustri" },
        { key: "stemma sopra l'arco", note: "scolpito e dipinto, il casato proclama sé stesso" },
        { key: "doppia porta a vetri", note: "piombati e colorati, filtrano una luce da chiesa" },
        { key: "campanello a cordone", note: "seta e fiocco, un suono cristallino all'interno" },
      ],
      steampunk: [
        { key: "porta blindata a volano", note: "una manovella e un volano d'acciaio, come una cassaforte" },
        { key: "serratura a combinazione", note: "rotelle numerate d'ottone invece della chiave" },
        { key: "battente automatico", note: "si apre con un sibilo quando premi una piastra" },
        { key: "spioncino a lente", note: "un occhio deformato ti scruta prima di aprire" },
        { key: "cartello di metallo", note: "'VIETATO L'INGRESSO' inciso e dipinto di rosso" },
        { key: "citofono a tromba", note: "parli in un imbuto d'ottone per farti annunciare" },
        { key: "guarnizioni di gomma", note: "sigillano contro il fumo, sibilano all'apertura" },
      ],
    },
    scale: {
      sfarzoso: [
        { key: "scalone di marmo", note: "rampe ampie, corrimano scolpito, un tappeto rosso al centro" },
        { key: "candelabri alle pareti", note: "ogni pochi passi, luce dorata e tremula" },
        { key: "ritratti in fila", note: "antenati severi che ti seguono con lo sguardo" },
        { key: "balaustra dorata", note: "volute eleganti, fredde e lisce sotto la mano" },
        { key: "specchi alti", note: "moltiplicano il corridoio e la tua immagine" },
        { key: "eco felpato", note: "i passi affondano nel tappeto, voci attutite" },
      ],
      steampunk: [
        { key: "scala a chiocciola di ferro", note: "gradini grigliati che risuonano a ogni passo" },
        { key: "montacarichi a gabbia", note: "sale cigolando lungo una guida a fianco" },
        { key: "tubi lungo il soffitto", note: "corrono paralleli al corridoio, caldi e ronzanti" },
        { key: "lampade a gas in fila", note: "a intervalli regolari, fischiano piano" },
        { key: "passerella metallica", note: "sospesa, vibra, sotto si vede il piano inferiore" },
        { key: "porta tagliafuoco", note: "pesante, a molla, si chiude da sé con un tonfo" },
        { key: "ringhiera unta", note: "l'olio delle mani di mille turni" },
      ],
    },
    soffitti: {
      sfarzoso: [
        { key: "volta affrescata", note: "cieli e angeli dipinti, oro tra le nuvole" },
        { key: "lampadario di cristallo", note: "decine di gocce che frantumano la luce" },
        { key: "stucchi dorati", note: "cornici e rosoni in rilievo, putti negli angoli" },
        { key: "travi dipinte", note: "motivi geometrici e stemmi su fondo blu" },
        { key: "lucernario a vetri colorati", note: "una pioggia di luce tinta sul pavimento" },
        { key: "cassettoni di legno", note: "intagliati e dorati, ognuno diverso" },
      ],
      steampunk: [
        { key: "capriate di ferro a vista", note: "rivetti e tiranti, una ragnatela industriale" },
        { key: "lucernari anneriti", note: "vetro opaco di fuliggine, una luce grigia" },
        { key: "tubature appese", note: "condotte e cavi sopra la testa, gocciolano" },
        { key: "ventole sul soffitto", note: "girano per estrarre il fumo, ronzio costante" },
        { key: "lampade industriali", note: "piatti di smalto che concentrano la luce in basso" },
        { key: "carro ponte", note: "una gru su rotaie attraversa lentamente lo spazio" },
        { key: "passerelle sospese", note: "operai camminano in alto, scintille cadono" },
      ],
    },
  },
  meteo: {
    nebbia: {
      sfarzoso: [
        { key: "foschia dorata all'alba", note: "il sole nascente la accende, i giardini sembrano sospesi" },
        { key: "lanterne aureolate", note: "ogni luce ha un alone soffuso, romantico" },
        { key: "nebbia che ovatta i suoni", note: "il parco diventa un quadro ovattato e ricco" },
        { key: "rugiada sui marmi", note: "le statue luccicano, perle su pietra pregiata" },
        { key: "vapore sulle fontane", note: "l'acqua tiepida fuma nell'aria fresca del mattino" },
        { key: "silhouette eleganti", note: "figure in mantello attraversano la foschia con grazia" },
      ],
      steampunk: [
        { key: "smog giallastro", note: "nebbia e fumo di carbone mescolati, sa di zolfo" },
        { key: "lampioni come aloni", note: "la luce a gas non buca la coltre, galleggia" },
        { key: "fischi ovattati", note: "treni e sirene attutiti, impossibile dire da dove" },
        { key: "sapore di carbone in bocca", note: "la foschia industriale si deposita sui denti" },
        { key: "sagome che appaiono di colpo", note: "un tram, un passante, sbucano a un passo" },
        { key: "fuliggine sospesa", note: "particelle nere che ti sporcano il colletto" },
        { key: "tosse generale", note: "la città intera schiarisce la gola nello smog" },
      ],
    },
    tempesta: {
      sfarzoso: [
        { key: "tempesta dalle vetrate", note: "lampi che illuminano una sala calda e dorata" },
        { key: "candelabri che tremolano", note: "a ogni tuono le fiamme vacillano, ombre lunghe" },
        { key: "pioggia sui tetti di rame", note: "un tamburo costante e ricco sopra il palazzo" },
        { key: "vento tra i drappi", note: "le tende ricamate si gonfiano alle finestre socchiuse" },
        { key: "fulmine sul giardino", note: "per un istante le statue brillano bianche" },
        { key: "camino ruggente", note: "il fuoco risponde al vento nella canna" },
      ],
      steampunk: [
        { key: "fulmini sui parafulmini", note: "ciminiere e antenne attirano scariche viola" },
        { key: "scarichi che esplodono", note: "la pioggia sulle valvole roventi sibila in vapore" },
        { key: "rivoli neri di carbone", note: "l'acqua lava la fuliggine in torrenti scuri" },
        { key: "tetti di lamiera rombanti", note: "la pioggia ci batte come una gragnola di chiodi" },
        { key: "cortocircuiti", note: "un lampione salta tra le scintille" },
        { key: "tram fermi", note: "i binari allagati, vagoni in coda sotto il diluvio" },
        { key: "fischi d'allarme", note: "qualcosa in fabbrica non regge alla tempesta" },
      ],
    },
    caldo: {
      sfarzoso: [
        { key: "ventagli e ghiaccio", note: "servitori sventolano, sorbetti in coppe d'argento" },
        { key: "fontane fresche", note: "zampilli nei cortili ombreggiati, mormorio rinfrescante" },
        { key: "tende parasole", note: "stoffe chiare sui terrazzi, ombra profumata" },
        { key: "logge ventilate", note: "correnti studiate attraversano le sale dei nobili" },
        { key: "vesti leggere di lino", note: "candide, impeccabili, mai una macchia di sudore" },
        { key: "limonata ghiacciata", note: "su vassoi, gocce di condensa sul cristallo" },
      ],
      steampunk: [
        { key: "calore delle fornaci", note: "alla canicola si somma quella delle macchine, irrespirabile" },
        { key: "operai madidi", note: "camicie incollate alla schiena, bevono da secchi d'acqua" },
        { key: "selciato che si ammorbidisce", note: "il catrame appiccica le suole" },
        { key: "ventole a tutta velocità", note: "spostano aria bollente, fanno solo rumore" },
        { key: "ghiaccio venduto a carretti", note: "blocchi in segatura, sciolti a metà" },
        { key: "puzza di fogna", note: "il caldo fa salire i miasmi dai tombini" },
        { key: "vapore che non si vede", note: "l'aria già rovente lo inghiotte appena esce" },
      ],
    },
    freddo: {
      sfarzoso: [
        { key: "neve sui giardini", note: "siepi e statue incipriate di bianco, un quadro immacolato" },
        { key: "pellicce pregiate", note: "volpe ed ermellino, niente brividi per i ricchi" },
        { key: "bracieri dorati", note: "carboni profumati scaldano le sale, riflessi caldi" },
        { key: "vetri ghiacciati a ricami", note: "il gelo disegna merletti sulle finestre alte" },
        { key: "slitta laccata", note: "campanelli d'argento, coperte di lana sui sedili" },
        { key: "vin brulé speziato", note: "fumante in coppe, cannella e chiodi di garofano" },
      ],
      steampunk: [
        { key: "vapore che gela in aria", note: "ogni sbuffo delle macchine diventa una nube bianca" },
        { key: "tubi che scoppiano", note: "l'acqua congelata spacca le condotte, perdite ovunque" },
        { key: "fuliggine sulla neve", note: "il bianco dura un'ora, poi è grigio di carbone" },
        { key: "operai ai bracieri", note: "guanti tagliati, mani sopra i bidoni in fiamme" },
        { key: "ghiaccio sui binari", note: "i tram slittano, spargisale al lavoro all'alba" },
        { key: "fiato e fumo insieme", note: "difficile dire cosa esce dalla bocca e cosa dai comignoli" },
        { key: "lampioni con cappucci di neve", note: "la luce a gas fatica a bucare il gelo" },
      ],
    },
  },
  suoni: {
    natura: {
      sfarzoso: [
        { key: "fruscio di fontane", note: "acqua incanalata che mormora tra siepi potate" },
        { key: "profumo di rose coltivate", note: "intenso e studiato, un roseto da esposizione" },
        { key: "cinguettii d'uccelliera", note: "specie rare in gabbie dorate, un concerto su misura" },
        { key: "ronzio d'api su lavanda", note: "filari ordinati, miele che profuma l'aria" },
        { key: "scricchiolio di ghiaia", note: "i vialetti curati cedono sotto passi eleganti" },
        { key: "odore di erba tagliata", note: "prati rasati di fresco, verde e fresco" },
      ],
      steampunk: [
        { key: "ronzio elettrico di fondo", note: "un brusio costante da qualche dinamo vicina" },
        { key: "odore di ozono", note: "metallico e pungente, come dopo un fulmine" },
        { key: "ticchettio di un congegno", note: "regolare, nascosto, da qualche parte nel verde" },
        { key: "fischio lontano di vapore", note: "rompe il silenzio del bosco a intervalli" },
        { key: "puzza d'olio su una pozza", note: "iridescente, fuori posto tra le foglie" },
        { key: "vibrazione nel terreno", note: "una macchina lavora sottoterra, la senti ai piedi" },
      ],
    },
    urbano: {
      sfarzoso: [
        { key: "carrozze e zoccoli", note: "il trotto cadenzato sul lastricato del quartiere alto" },
        { key: "profumo di pasticceria", note: "burro e zucchero da una vetrina elegante" },
        { key: "musica da un salone", note: "un pianoforte da finestre illuminate" },
        { key: "voci educate", note: "conversazioni misurate, risate trattenute" },
        { key: "campane festose", note: "una festa nobiliare, rintocchi allegri" },
        { key: "incenso da una cappella", note: "dolce, sale da un portone socchiuso" },
      ],
      steampunk: [
        { key: "frastuono dei magli", note: "un battito costante che scuote i vetri da lontano" },
        { key: "sferragliare di tram", note: "ferro su ferro, una campanella, sbuffi a ogni fermata" },
        { key: "puzza di carbone e fogna", note: "il respiro stesso della città industriale" },
        { key: "fischi di fabbrica", note: "scandiscono i turni, tutta la città li conosce" },
        { key: "strilloni di giornali", note: "gridano i titoli sulla rivoluzione all'angolo" },
        { key: "ronzio dei cavi", note: "le linee elettriche cantano sopra le teste" },
        { key: "clacson e campanelli", note: "veicoli a vapore che si contendono la strada" },
        { key: "odore di olio e benzina", note: "dolciastro e nuovo, dei pochi motori che ci sono" },
        { key: "sirena di cambio turno", note: "un ululato lungo che svuota o riempie le strade" },
        { key: "martello sul ferro lontano", note: "un'officina che non chiude mai, ritmico nella notte" },
        { key: "voci di protesta", note: "un coro compatto che sale da una piazza, scandito a slogan" },
        { key: "stridore di freni", note: "metallo su metallo a una fermata del tram" },
        { key: "borbottio di un motore", note: "irregolare, da un veicolo fermo che qualcuno bestemmia" },
        { key: "richiami degli ambulanti", note: "castagne, giornali, fiammiferi, gridati a turno" },
        { key: "tonfo di carbone", note: "una cascata che riempie una cantina da una botola" },
      ],
    },
    interni: {
      sfarzoso: [
        { key: "scricchiolio del parquet", note: "legno pregiato sotto tappeti spessi" },
        { key: "tintinnio di cristalli", note: "calici e lampadari rispondono a ogni passo" },
        { key: "profumo di cera e fiori", note: "ambienti curati, vasi freschi ogni giorno" },
        { key: "fruscio di sete", note: "abiti che strusciano nei corridoi" },
        { key: "ticchettio di un pendolo", note: "un orologio prezioso scandisce la quiete" },
        { key: "voci ovattate", note: "le pareti spesse attutiscono tutto in un mormorio" },
      ],
      steampunk: [
        { key: "ronzio di lampade a gas", note: "un sibilo costante appena sotto l'udibile" },
        { key: "ticchettio di mille ingranaggi", note: "da una stanza accanto, un meccanismo non si ferma" },
        { key: "odore di olio caldo", note: "macchine al lavoro dietro una parete" },
        { key: "sbuffi di valvole", note: "a intervalli irregolari, vapore che si sfoga" },
        { key: "vibrazione del pavimento", note: "qualcosa di pesante gira al piano di sotto" },
        { key: "fischio del bollitore", note: "acuto e prolungato, finché qualcuno non lo toglie" },
        { key: "scatto di interruttori", note: "relè e leve che si chiudono con un clack metallico" },
      ],
    },
  },
  oggetti: {
    trovati: {
      sfarzoso: [
        { key: "tabacchiera smaltata", note: "una miniatura dipinta sul coperchio, ancora profumata" },
        { key: "anello con sigillo", note: "uno stemma inciso, un casato che qualcuno riconoscerà" },
        { key: "ventaglio di pizzo", note: "stecche d'avorio, un monogramma ricamato" },
        { key: "orologio da tasca d'oro", note: "inciso a mano, una dedica dentro il coperchio" },
        { key: "fiala di profumo", note: "cristallo molato, un'essenza rara quasi finita" },
        { key: "medaglione con ritratto", note: "una dama in miniatura, una ciocca di capelli" },
      ],
      steampunk: [
        { key: "valvola di ricambio", note: "ottone lucido, filettatura nuova, mai usata" },
        { key: "biglietto del tram", note: "stampato e forato, una data di pochi giorni fa" },
        { key: "occhiali da officina", note: "una lente incrinata, cinghia consumata" },
        { key: "schema piegato", note: "il disegno quotato di un meccanismo, note a matita" },
        { key: "chiave inglese", note: "il manico segnato da una sigla incisa col punzone" },
        { key: "capsula pneumatica", note: "vuota, ancora calda, da un tubo di smistamento" },
        { key: "spilla del sindacato", note: "smalto scrostato, la porta chi rischia il posto" },
        { key: "fiala di tonico", note: "etichetta a stampa, mezza bevuta, odore chimico" },
        { key: "ingranaggio spaiato", note: "denti consumati, caduto da qualcosa di più grande" },
      ],
    },
    arredo: {
      sfarzoso: [
        { key: "poltrona di velluto", note: "schienale alto, chiodini dorati, profumo di stanza chiusa" },
        { key: "specchio dalla cornice intagliata", note: "oro annerito agli angoli, vetro ondulato" },
        { key: "scrittoio intarsiato", note: "legni diversi a comporre motivi, cassetti segreti forse" },
        { key: "arazzo alla parete", note: "una scena di caccia sbiadita, fili d'oro che resistono" },
        { key: "candelabro a cinque braccia", note: "argento ossidato, cera colata e indurita" },
        { key: "vetrina di curiosità", note: "cammei, conchiglie, una collezione orgogliosa" },
      ],
      steampunk: [
        { key: "macchina da scrivere", note: "tasti d'ottone, un foglio a metà battuto" },
        { key: "lampada a gas snodabile", note: "braccio articolato, paralume di vetro verde" },
        { key: "schedario metallico", note: "cassetti numerati, etichette dattiloscritte" },
        { key: "poltrona di cuoio e rivetti", note: "logora, rattoppata con nastro, comodissima" },
        { key: "orologio a ingranaggi a vista", note: "un ticchettio rassicurante dietro il vetro" },
        { key: "stufa di ghisa", note: "tubo che sale al soffitto, ancora tiepida" },
        { key: "telefono a parete", note: "una cornetta su forcella, manovella sul lato" },
        { key: "pila di cianografie", note: "disegni tecnici arrotolati, polverosi, legati con spago" },
      ],
    },
    indossati: {
      sfarzoso: [
        { key: "mantello foderato di seta", note: "fermaglio gemmato, l'orlo mai sfiorato dal fango" },
        { key: "guanti di capretto", note: "cuciture invisibili, bottoncini di perla al polso" },
        { key: "scarpe con fibbia d'argento", note: "tacco alto, suola che non ha mai visto la strada" },
        { key: "cappello piumato", note: "una piuma esotica, tinta in un colore costoso" },
        { key: "spilla a forma di fiore", note: "petali di smalto e un brillante al centro" },
        { key: "bastone da passeggio", note: "pomo d'avorio, più ornamento che sostegno" },
      ],
      steampunk: [
        { key: "occhiali sulla bombetta", note: "cinghia di cuoio, lenti graffiate dall'uso" },
        { key: "panciotto con orologio", note: "catena d'ottone, tasca consumata dall'abitudine" },
        { key: "guanti senza dita", note: "macchiati d'olio, per il lavoro fine sul metallo" },
        { key: "spilla a ingranaggio", note: "ottone brunito, un piccolo orgoglio operaio" },
        { key: "cappotto con mille tasche", note: "ognuna un attrezzo, tintinna quando cammina" },
        { key: "maschera antifumo al collo", note: "abbassata, pronta per i fumi della fabbrica" },
        { key: "stivali rinforzati in punta", note: "acciaio sotto il cuoio, segnati dalle schegge" },
        { key: "bracciale di rame", note: "lo portano in molti, dicono protegga dalle scariche" },
      ],
    },
  },
};
